server:
  port: 9000

spring:
  application:
    name: cards

  profiles:
    active: "prod"

  config:
    import: "optional:configserver:http://localhost:8071/"

  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true

  cloud:
    stream:
      bindings:
        sendConfirmation-out-0:
          destination: send-confirmation

      kafka:
        binder:
          brokers:
            - localhost:9092

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Easy Bank Cards Application"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: "cards"

logging:
  level:
    com:
      easybank:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"



#  datasource:
#    url: jdbc:mysql://localhost:3308/cardsdb
#    username: root
#    password: root
#
#  sql:
#   init:
#    mode: always
#
#  jpa:
#   show-sql: true