
spring:
  application:
   name: gatewayserver

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s

  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

  endpoint:
    gateway:
      enabled: true

  metrics:
    tags:
      application: "gatewayserver"


info:
  app:
    name: "gatewayserver"
    description: "Easybank gateway server application"
    version: "1.0.0"

logging:
  level:
    com:
      easybank:
        gatewayserver: DEBUG


resilience4j.circuitbreaker:
  config:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000