services:
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "aswinsenniappan/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config
    healthcheck:
      test: [ "CMD-SHELL", "true"]
      interval: 10s
      timeout: 30s
      retries: 10

  accounts:
    image: "aswinsenniappan/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
     configserver:
       condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: accounts
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "aswinsenniappan/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
       configserver:
         condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: loans
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  cards:
    image: "aswinsenniappan/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: cards
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"