encrypt:
  key: CB79DCD7F777C8B3FEFAE9FF29EFD

server:
  port: 8071

spring:
  application:
   name: "configserver"

  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Aswin850/easybank-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

#          search-locations: "file:/Users/asenniappan/eclipse-workspace/microServices/document/config"
#          search-location: "classpath:/config"


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  matrics:
    tags:
      application: "configserver"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
